host: ""
port: 8317

# Trỏ mọi thứ vào thư mục /data sẽ mount trên server
auth-dir: "/data/auths"
logging-to-file: true
logs-max-total-size-mb: 100

remote-management:
  allow-remote: true
  # secret-key được quản lý qua biến môi trường MANAGEMENT_PASSWORD

api-keys:
  - "mun-key-01"

oauth-model-alias:
  antigravity:
    - name: "rev19-uic3-1p"
      alias: "gemini-2.5-computer-use-preview-10-2025"
