version: '3.8'

services:
  cli-proxy-api:
    image: eceasy/cli-proxy-api:latest
    container_name: cli-proxy-api
    pull_policy: always
    environment:
      # BẮT BUỘC: Chế độ tự động cấu hình cho Dokploy
      - DEPLOY=dokploy
      # Mật khẩu quản trị
      - MANAGEMENT_PASSWORD=Chinhniem@0602
    ports:
      - "8317:8317"
      - "8085:8085"
      - "1455:1455"
      - "54545:54545"
    volumes:
      # Dùng relative path để Dokploy tự nhận file trong repo
      - ./config.yaml:/CLIProxyAPI/config.yaml
      - ./auths:/root/.cli-proxy-api
      - ./logs:/CLIProxyAPI/logs
    restart: unless-stopped